# Generated by Django 4.2.3 on 2023-08-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(verbose_name='Candidate ID')),
                ('cname', models.CharField(max_length=200, verbose_name='Candidate Name')),
                ('partyname', models.CharField(max_length=200, verbose_name='Party Name')),
                ('symbol', models.ImageField(upload_to='candidate/', verbose_name='Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.IntegerField(verbose_name='Voter ID')),
                ('voter_name', models.CharField(max_length=200, verbose_name='Voter Name')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
